name: lua

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
         luaVersion: ["luajit"]

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Install
      run: |
        sudo apt update && \
        sudo apt install -y build-essential libreadline-dev zip unzip cmake wget luajit libluajit-5.1-dev && \
        wget https://github.com/luarocks/luarocks/releases/download/v3.12.2/luarocks-3.12.2.tar.gz && \
        tar zxpf luarocks-3.12.2.tar.gz && \
        cd luarocks-3.12.2 && \
        ./configure && \
        make && sudo make install && \
        cd .. && \
        rm -rf luarocks-3.8.1.2 && \
        rm luarocks-3.12.2.tar.gz && \
        luarocks install busted && \
        luarocks install rapidjson 0.7.1 && \
        luarocks install luasocket && \
        luarocks install lua-resty-openssl 0.8.8-1 && \
        luarocks install date 2.1.2-1
    - name: Test
      run: busted spec